# config.yaml
# Configuration file for the document parsing project.

# Get your free API key from https://ocr.space/
ocr_space_api_key: "K88629238088957"

# --- File Paths ---
# Define the input directory for PDFs and the output for JSON files.
# You can use relative paths (e.g., "pdfs") or absolute paths 
# (e.g., "D:/Cases/Input" on Windows or "/Users/user/docs/Input" on macOS).
paths:
  input_directory: "New_reports"
  output_directory: "json_generator\\output"